"""Versioned producer and consumer contract for desktop release artifacts."""

from __future__ import annotations

from tongs.desktop.artifact_contract.archive import (
    INSTALL_MANIFEST_PATH,
    inspect_archive,
    select_release_artifact,
    validate_archive_layout,
    validate_artifact_archive,
    validate_manifest_pair,
)
from tongs.desktop.artifact_contract.manifests import (
    FIXED_APP_ASAR_PATH,
    FIXED_LAUNCHER_PATH,
    FIXED_LICENSE_INVENTORY_PATH,
    INSTALL_SCHEMA_VERSION,
    RELEASE_SCHEMA_VERSION,
    parse_install_manifest,
    parse_release_manifest,
)
from tongs.desktop.artifact_contract.models import (
    ArchiveEntry,
    ArchiveEntryType,
    ArchiveInspection,
    ArtifactContractError,
    ArtifactContractErrorCode,
    ArtifactOwnership,
    DesktopArtifact,
    DesktopCompatibility,
    DesktopInstallManifest,
    DesktopPlatform,
    DesktopReleaseManifest,
    ExtractionLimits,
    InstallFile,
    PackageKind,
    TargetArchitecture,
    TargetOperatingSystem,
    ValidatedArchiveLayout,
    ValidatedArtifactContract,
)
from tongs.desktop.artifact_contract.schema_resources import (
    INSTALL_SCHEMA_NAME,
    RELEASE_SCHEMA_NAME,
    install_schema_bytes,
    release_schema_bytes,
)

__all__ = [
    "FIXED_APP_ASAR_PATH",
    "FIXED_LAUNCHER_PATH",
    "FIXED_LICENSE_INVENTORY_PATH",
    "INSTALL_MANIFEST_PATH",
    "INSTALL_SCHEMA_NAME",
    "INSTALL_SCHEMA_VERSION",
    "RELEASE_SCHEMA_NAME",
    "RELEASE_SCHEMA_VERSION",
    "ArchiveEntry",
    "ArchiveEntryType",
    "ArchiveInspection",
    "ArtifactContractError",
    "ArtifactContractErrorCode",
    "ArtifactOwnership",
    "DesktopArtifact",
    "DesktopCompatibility",
    "DesktopInstallManifest",
    "DesktopPlatform",
    "DesktopReleaseManifest",
    "ExtractionLimits",
    "InstallFile",
    "PackageKind",
    "TargetArchitecture",
    "TargetOperatingSystem",
    "ValidatedArchiveLayout",
    "ValidatedArtifactContract",
    "inspect_archive",
    "install_schema_bytes",
    "parse_install_manifest",
    "parse_release_manifest",
    "release_schema_bytes",
    "select_release_artifact",
    "validate_archive_layout",
    "validate_artifact_archive",
    "validate_manifest_pair",
]
